"""Initialization data for event attribute system (40 categories, 400-550 subcategories)."""

EVENT_CATEGORIES = [
    {"code": "politics_government", "name": "政府会议", "description": "各级政府及相关部门召开的各类会议", "sort_order": 1},
    {"code": "policy_release", "name": "政策发布", "description": "政府及相关部门发布的各类政策、法规、通知等", "sort_order": 2},
    {"code": "personnel_appointment", "name": "人事任免", "description": "领导干部的任免、调动等人事变动", "sort_order": 3},
    {"code": "inspection_research", "name": "视察调研", "description": "领导干部的视察、调研、考察等活动", "sort_order": 4},
    {"code": "diplomatic_visit", "name": "外交访问", "description": "国内外领导人的互访、外交活动等", "sort_order": 5},
    {"code": "international_meeting", "name": "国际会议", "description": "各类国际会议、论坛、峰会等", "sort_order": 6},
    {"code": "economic_trade", "name": "经贸合作", "description": "经济贸易合作、项目签约等活动", "sort_order": 7},
    {"code": "investment_attraction", "name": "投资招商", "description": "招商引资、项目推介等活动", "sort_order": 8},
    {"code": "financial_market", "name": "金融市场", "description": "金融市场动态、货币政策等", "sort_order": 9},
    {"code": "enterprise_dynamic", "name": "企业动态", "description": "企业的经营、发展、合作等动态", "sort_order": 10},
    {"code": "tech_innovation", "name": "科技创新", "description": "科技创新、技术突破等", "sort_order": 11},
    {"code": "academic_research", "name": "学术研究", "description": "学术研究成果、论文发表等", "sort_order": 12},
    {"code": "education_reform", "name": "教育改革", "description": "教育体制改革、政策调整等", "sort_order": 13},
    {"code": "admission_exam", "name": "招生考试", "description": "各类招生、考试信息", "sort_order": 14},
    {"code": "campus_life", "name": "校园生活", "description": "校园内的各类活动、学生生活等", "sort_order": 15},
    {"code": "medical_reform", "name": "医疗改革", "description": "医疗体制改革、医保政策等", "sort_order": 16},
    {"code": "public_health", "name": "公共卫生", "description": "公共卫生事件、健康宣传等", "sort_order": 17},
    {"code": "disease_prevention", "name": "疾病防控", "description": "传染病防控、疫苗接种等", "sort_order": 18},
    {"code": "cultural_activity", "name": "文化活动", "description": "各类文化活动、节庆等", "sort_order": 19},
    {"code": "art_exhibition", "name": "艺术展览", "description": "各类艺术展览、博物馆活动等", "sort_order": 20},
    {"code": "sports_event", "name": "体育赛事", "description": "各类体育比赛、赛事活动", "sort_order": 21},
    {"code": "fitness_exercise", "name": "全民健身", "description": "全民健身运动、体育活动等", "sort_order": 22},
    {"code": "tourism_development", "name": "旅游发展", "description": "旅游业发展、旅游政策等", "sort_order": 23},
    {"code": "scenic_dynamic", "name": "景区动态", "description": "旅游景区的动态、活动等", "sort_order": 24},
    {"code": "environmental_protection", "name": "环境保护", "description": "环境保护政策、措施等", "sort_order": 25},
    {"code": "ecological_construction", "name": "生态建设", "description": "生态建设、生态保护等", "sort_order": 26},
    {"code": "transport_construction", "name": "交通建设", "description": "交通基础设施建设", "sort_order": 27},
    {"code": "traffic_accident", "name": "交通事故", "description": "各类交通事故", "sort_order": 28},
    {"code": "safety_production", "name": "安全生产", "description": "安全生产、安全检查等", "sort_order": 29},
    {"code": "disaster_accident", "name": "灾害事故", "description": "自然灾害、事故灾难等", "sort_order": 30},
    {"code": "social_security", "name": "社会治安", "description": "社会治安、维稳等", "sort_order": 31},
    {"code": "judicial_case", "name": "司法案件", "description": "各类司法案件、法律事件", "sort_order": 32},
    {"code": "social_insurance", "name": "社会保障", "description": "社会保障、福利等", "sort_order": 33},
    {"code": "people_livelihood", "name": "民生服务", "description": "民生服务、便民措施等", "sort_order": 34},
    {"code": "rural_revitalization", "name": "乡村振兴", "description": "乡村振兴、农业农村发展", "sort_order": 35},
    {"code": "urban_construction", "name": "城市建设", "description": "城市建设、城市管理等", "sort_order": 36},
    {"code": "market_supervision", "name": "市场监管", "description": "市场监管、价格管理等", "sort_order": 37},
    {"code": "consumer_rights", "name": "消费维权", "description": "消费者权益保护", "sort_order": 38},
    {"code": "weather_warning", "name": "气象预警", "description": "气象预警、天气预报等", "sort_order": 39},
    {"code": "emergency_event", "name": "突发事件", "description": "各类突发事件、应急响应", "sort_order": 40},
]

EVENT_SUBCATEGORIES = {
    "politics_government": [
        {"code": "standing_committee", "name": "常委会议", "description": "党委常委会会议"},
        {"code": "government_meeting", "name": "政府常务会", "description": "政府常务会议"},
        {"code": "plenary_meeting", "name": "全体会议", "description": "政府全体会议"},
        {"code": "work_conference", "name": "工作会议", "description": "各类工作会议"},
        {"code": "special_meeting", "name": "专题会议", "description": "专题研究会议"},
        {"code": "coordination_meeting", "name": "协调会议", "description": "协调推进会议"},
        {"code": "briefing_meeting", "name": "通报会议", "description": "情况通报会议"},
        {"code": "deployment_meeting", "name": "部署会议", "description": "工作部署会议"},
        {"code": "summary_meeting", "name": "总结会议", "description": "工作总结会议"},
        {"code": "training_meeting", "name": "培训会议", "description": "业务培训会议"},
        {"code": "symposium", "name": "座谈会", "description": "各类座谈会"},
        {"code": "seminar", "name": "研讨会", "description": "学术研讨会"},
    ],
    "policy_release": [
        {"code": "policy_document", "name": "政策文件", "description": "各类政策文件发布"},
        {"code": "regulation_announcement", "name": "法规公告", "description": "法律法规公告"},
        {"code": "notice_announcement", "name": "通知公告", "description": "各类通知公告"},
        {"code": "opinion_consultation", "name": "意见征集", "description": "政策意见征集"},
        {"code": "policy_interpretation", "name": "政策解读", "description": "政策解读文章"},
        {"code": "implementation_opinion", "name": "实施意见", "description": "实施意见发布"},
        {"code": "work_plan", "name": "工作计划", "description": "年度工作计划"},
        {"code": "development_plan", "name": "发展规划", "description": "中长期发展规划"},
        {"code": "technical_specification", "name": "技术规范", "description": "技术标准规范"},
        {"code": "management_measure", "name": "管理办法", "description": "各类管理办法"},
    ],
    "personnel_appointment": [
        {"code": "leadership_appointment", "name": "领导任职", "description": "领导干部任职"},
        {"code": "leadership_removal", "name": "领导免职", "description": "领导干部免职"},
        {"code": "personnel_transfer", "name": "人事调动", "description": "干部工作调动"},
        {"code": "retirement_announcement", "name": "退休公告", "description": "干部退休公告"},
        {"code": "resignation_announcement", "name": "辞职公告", "description": "干部辞职公告"},
        {"code": "recruitment_announcement", "name": "招聘公告", "description": "事业单位招聘"},
        {"code": "selection_announcement", "name": "遴选公告", "description": "公务员遴选"},
        {"code": "promotion_announcement", "name": "提拔公示", "description": "干部提拔公示"},
        {"code": "evaluation_result", "name": "考核结果", "description": "干部考核结果"},
        {"code": "honor_recognition", "name": "荣誉表彰", "description": "先进个人表彰"},
    ],
    "inspection_research": [
        {"code": "leader_inspection", "name": "领导视察", "description": "领导干部视察"},
        {"code": "field_research", "name": "实地调研", "description": "实地调研活动"},
        {"code": "enterprise_visit", "name": "企业走访", "description": "走访企业调研"},
        {"code": "community_research", "name": "社区调研", "description": "社区基层调研"},
        {"code": "rural_research", "name": "乡村调研", "description": "农村地区调研"},
        {"code": "project_inspection", "name": "项目检查", "description": "工程项目检查"},
        {"code": "supervision_inspection", "name": "督查检查", "description": "工作督查检查"},
        {"code": "special_survey", "name": "专项调查", "description": "专项调查研究"},
        {"code": "overseas_investigation", "name": "外出考察", "description": "外出学习考察"},
        {"code": "research_report", "name": "调研报告", "description": "调研报告发布"},
    ],
    "diplomatic_visit": [
        {"code": "foreign_leader_visit", "name": "外宾来访", "description": "外国领导人来访"},
        {"code": "domestic_leader_visit", "name": "领导出访", "description": "国内领导人出访"},
        {"code": "diplomatic_meeting", "name": "外交会晤", "description": "外交会晤活动"},
        {"code": "agreement_signing", "name": "协议签署", "description": "合作协议签署"},
        {"code": "consulate_activity", "name": "领馆活动", "description": "领事馆活动"},
        {"code": "cultural_exchange", "name": "文化交流", "description": "对外文化交流"},
        {"code": "economic_cooperation", "name": "经贸交流", "description": "对外经贸交流"},
        {"code": "friendship_city", "name": "友好城市", "description": "友好城市活动"},
        {"code": "overseas_chinese", "name": "侨务工作", "description": "侨务相关活动"},
        {"code": "international_aid", "name": "国际援助", "description": "国际援助活动"},
    ],
    "international_meeting": [
        {"code": "international_forum", "name": "国际论坛", "description": "各类国际论坛"},
        {"code": "international_summit", "name": "国际峰会", "description": "国际领导人峰会"},
        {"code": "bilateral_meeting", "name": "双边会谈", "description": "双边会谈活动"},
        {"code": "multilateral_meeting", "name": "多边会谈", "description": "多边会谈活动"},
        {"code": "regional_meeting", "name": "区域会议", "description": "区域合作会议"},
        {"code": "international_organization", "name": "国际组织", "description": "国际组织会议"},
        {"code": "trade_negotiation", "name": "贸易谈判", "description": "国际贸易谈判"},
        {"code": "security_meeting", "name": "安全会议", "description": "国际安全会议"},
        {"code": "environmental_meeting", "name": "环境会议", "description": "国际环境会议"},
        {"code": "health_meeting", "name": "卫生会议", "description": "国际卫生会议"},
    ],
    "economic_trade": [
        {"code": "trade_agreement", "name": "贸易协定", "description": "贸易协定签署"},
        {"code": "investment_project", "name": "投资项目", "description": "投资项目签约"},
        {"code": "economic_cooperation_zone", "name": "合作园区", "description": "经济合作园区"},
        {"code": "trade_fair", "name": "贸易展会", "description": "各类贸易展会"},
        {"code": "import_export", "name": "进出口", "description": "进出口贸易"},
        {"code": "border_trade", "name": "边境贸易", "description": "边境贸易活动"},
        {"code": "ecommerce_trade", "name": "跨境电商", "description": "跨境电子商务"},
        {"code": "trade_facilitation", "name": "贸易便利", "description": "贸易便利化措施"},
        {"code": "customs_clearance", "name": "通关服务", "description": "海关通关服务"},
        {"code": "logistics_service", "name": "物流服务", "description": "物流配套服务"},
    ],
    "investment_attraction": [
        {"code": "investment_promotion", "name": "投资推介", "description": "投资推介活动"},
        {"code": "project_signing", "name": "项目签约", "description": "项目签约仪式"},
        {"code": "investment_landing", "name": "项目落地", "description": "投资项目落地"},
        {"code": "investment_environment", "name": "投资环境", "description": "投资环境介绍"},
        {"code": "investment_policy", "name": "招商政策", "description": "招商引资政策"},
        {"code": "investment_service", "name": "企业服务", "description": "企业服务措施"},
        {"code": "industrial_park", "name": "产业园区", "description": "产业园区招商"},
        {"code": "key_project", "name": "重点项目", "description": "重点项目推进"},
        {"code": "investment_statistics", "name": "招商统计", "description": "招商引资统计"},
        {"code": "investment_achievement", "name": "招商成果", "description": "招商引资成果"},
    ],
    "financial_market": [
        {"code": "stock_market", "name": "股票市场", "description": "股票市场动态"},
        {"code": "bond_market", "name": "债券市场", "description": "债券市场动态"},
        {"code": "fund_market", "name": "基金市场", "description": "基金市场动态"},
        {"code": "insurance_market", "name": "保险市场", "description": "保险市场动态"},
        {"code": "banking_industry", "name": "银行业", "description": "银行业动态"},
        {"code": "monetary_policy", "name": "货币政策", "description": "货币政策调整"},
        {"code": "interest_rate", "name": "利率动态", "description": "利率变化情况"},
        {"code": "exchange_rate", "name": "汇率动态", "description": "汇率变化情况"},
        {"code": "financial_risk", "name": "金融风险", "description": "金融风险防控"},
        {"code": "financial_regulation", "name": "金融监管", "description": "金融监管政策"},
    ],
    "enterprise_dynamic": [
        {"code": "enterprise_operation", "name": "企业经营", "description": "企业经营情况"},
        {"code": "enterprise_cooperation", "name": "企业合作", "description": "企业合作动态"},
        {"code": "enterprise_merger", "name": "企业并购", "description": "企业并购重组"},
        {"code": "enterprise_listing", "name": "企业上市", "description": "企业上市动态"},
        {"code": "product_release", "name": "产品发布", "description": "新产品发布"},
        {"code": "technology_upgrade", "name": "技术升级", "description": "企业技术升级"},
        {"code": "market_expansion", "name": "市场拓展", "description": "企业市场拓展"},
        {"code": "talent_recruitment", "name": "人才招聘", "description": "企业人才招聘"},
        {"code": "corporate_culture", "name": "企业文化", "description": "企业文化建设"},
        {"code": "social_responsibility", "name": "社会责任", "description": "企业社会责任"},
    ],
    "tech_innovation": [
        {"code": "tech_breakthrough", "name": "技术突破", "description": "关键技术突破"},
        {"code": "invention_patent", "name": "发明专利", "description": "专利申请授权"},
        {"code": "tech_achievement", "name": "科技成果", "description": "科技成果转化"},
        {"code": "innovation_platform", "name": "创新平台", "description": "创新平台建设"},
        {"code": "r_d_investment", "name": "研发投入", "description": "研发经费投入"},
        {"code": "tech_enterprise", "name": "科技企业", "description": "高新技术企业"},
        {"code": "tech_industry", "name": "科技产业", "description": "科技产业发展"},
        {"code": "digital_transformation", "name": "数字化转型", "description": "企业数字化转型"},
        {"code": "smart_technology", "name": "智能化", "description": "智能化技术应用"},
        {"code": "tech_exchange", "name": "科技交流", "description": "科技交流活动"},
    ],
    "academic_research": [
        {"code": "academic_paper", "name": "论文发表", "description": "学术论文发表"},
        {"code": "research_project", "name": "科研项目", "description": "科研项目立项"},
        {"code": "research_funding", "name": "科研经费", "description": "科研经费申请"},
        {"code": "academic_conference", "name": "学术会议", "description": "学术会议活动"},
        {"code": "research_institution", "name": "科研机构", "description": "科研机构建设"},
        {"code": "research_team", "name": "科研团队", "description": "科研团队建设"},
        {"code": "laboratory", "name": "实验室", "description": "重点实验室建设"},
        {"code": "academic_exchange", "name": "学术交流", "description": "学术交流合作"},
        {"code": "research_award", "name": "科研奖励", "description": "科研成果奖励"},
        {"code": "technology_transfer", "name": "技术转移", "description": "科技成果转移"},
    ],
    "education_reform": [
        {"code": "curriculum_reform", "name": "课程改革", "description": "课程体系改革"},
        {"code": "teaching_reform", "name": "教学改革", "description": "教学方法改革"},
        {"code": "evaluation_reform", "name": "评价改革", "description": "教育评价改革"},
        {"code": "admission_reform", "name": "招生改革", "description": "招生制度改革"},
        {"code": "teacher_reform", "name": "教师改革", "description": "教师队伍建设"},
        {"code": "education_equity", "name": "教育公平", "description": "教育公平推进"},
        {"code": "quality_education", "name": "素质教育", "description": "素质教育推进"},
        {"code": "vocational_education", "name": "职业教育", "description": "职业教育发展"},
        {"code": "higher_education", "name": "高等教育", "description": "高等教育改革"},
        {"code": "basic_education", "name": "基础教育", "description": "基础教育改革"},
    ],
    "admission_exam": [
        {"code": "college_entrance", "name": "高考", "description": "普通高等学校招生考试"},
        {"code": "high_school_entrance", "name": "中考", "description": "高中阶段招生考试"},
        {"code": "postgraduate_exam", "name": "考研", "description": "研究生入学考试"},
        {"code": "civil_service_exam", "name": "公务员考试", "description": "公务员录用考试"},
        {"code": "teacher_qualification", "name": "教师资格证", "description": "教师资格考试"},
        {"code": "professional_qualification", "name": "职业资格", "description": "职业资格考试"},
        {"code": "language_test", "name": "语言考试", "description": "各类语言能力考试"},
        {"code": "admission_policy", "name": "招生政策", "description": "各类招生政策"},
        {"code": "exam_arrangement", "name": "考试安排", "description": "考试时间安排"},
        {"code": "score_query", "name": "成绩查询", "description": "考试成绩查询"},
    ],
    "campus_life": [
        {"code": "campus_activity", "name": "校园活动", "description": "各类校园活动"},
        {"code": "student_club", "name": "学生社团", "description": "学生社团活动"},
        {"code": "sports_meeting", "name": "运动会", "description": "学校运动会"},
        {"code": "art_festival", "name": "艺术节", "description": "校园文化艺术节"},
        {"code": "science_fair", "name": "科技节", "description": "校园科技节活动"},
        {"code": "reading_activity", "name": "读书活动", "description": "校园读书活动"},
        {"code": "volunteer_service", "name": "志愿服务", "description": "学生志愿服务"},
        {"code": "social_practice", "name": "社会实践", "description": "学生社会实践"},
        {"code": "mental_health", "name": "心理健康", "description": "心理健康教育"},
        {"code": "campus_security", "name": "校园安全", "description": "校园安全管理"},
    ],
    "medical_reform": [
        {"code": "medical_insurance", "name": "医保改革", "description": "医疗保险制度改革"},
        {"code": "hospital_reform", "name": "医院改革", "description": "公立医院改革"},
        {"code": "drug_system", "name": "药品制度", "description": "药品供应保障制度"},
        {"code": "medical_price", "name": "医疗价格", "description": "医疗服务价格调整"},
        {"code": "grading_diagnosis", "name": "分级诊疗", "description": "分级诊疗制度建设"},
        {"code": "family_doctor", "name": "家庭医生", "description": "家庭医生签约服务"},
        {"code": "telemedicine", "name": "远程医疗", "description": "远程医疗服务"},
        {"code": "medical_security", "name": "医疗保障", "description": "医疗保障体系建设"},
        {"code": "private_medical", "name": "社会办医", "description": "社会办医发展"},
        {"code": "medical_ethics", "name": "医德医风", "description": "医德医风建设"},
    ],
    "public_health": [
        {"code": "health_education", "name": "健康教育", "description": "健康知识宣传教育"},
        {"code": "health_promotion", "name": "健康促进", "description": "健康促进活动"},
        {"code": "chronic_disease", "name": "慢性病", "description": "慢性病防控管理"},
        {"code": "mental_health_service", "name": "精神卫生", "description": "精神卫生服务"},
        {"code": "maternal_child_health", "name": "妇幼保健", "description": "妇幼保健服务"},
        {"code": "elderly_health", "name": "老年健康", "description": "老年健康服务"},
        {"code": "occupational_health", "name": "职业健康", "description": "职业健康防护"},
        {"code": "environmental_health", "name": "环境卫生", "description": "环境卫生监测"},
        {"code": "food_safety", "name": "食品安全", "description": "食品安全监管"},
        {"code": "health_statistics", "name": "健康统计", "description": "健康统计数据"},
    ],
    "disease_prevention": [
        {"code": "epidemic_prevention", "name": "传染病防控", "description": "传染病预防控制"},
        {"code": "vaccination", "name": "疫苗接种", "description": "疫苗接种工作"},
        {"code": "epidemic_monitoring", "name": "疫情监测", "description": "传染病疫情监测"},
        {"code": "epidemic_response", "name": "疫情响应", "description": "疫情应急响应"},
        {"code": "quarantine_management", "name": "检疫管理", "description": "国境卫生检疫"},
        {"code": "disinfection_work", "name": "消毒工作", "description": "消毒杀菌工作"},
        {"code": "vector_control", "name": "病媒防控", "description": "病媒生物防控"},
        {"code": "emergency_management", "name": "应急管理", "description": "突发公共卫生事件"},
        {"code": "epidemic_education", "name": "防疫宣传", "description": "防疫知识宣传"},
        {"code": "epidemic_supply", "name": "防疫物资", "description": "防疫物资保障"},
    ],
    "cultural_activity": [
        {"code": "cultural_festival", "name": "文化节庆", "description": "各类文化节庆活动"},
        {"code": "cultural_performance", "name": "文艺演出", "description": "各类文艺演出"},
        {"code": "cultural_exhibition", "name": "文化展览", "description": "各类文化展览"},
        {"code": "cultural_lecture", "name": "文化讲座", "description": "各类文化讲座"},
        {"code": "book_fair", "name": "书展", "description": "图书展销活动"},
        {"code": "film_festival", "name": "电影节", "description": "各类电影节活动"},
        {"code": "music_festival", "name": "音乐节", "description": "各类音乐节活动"},
        {"code": "dance_festival", "name": "舞蹈节", "description": "各类舞蹈节活动"},
        {"code": "drama_festival", "name": "戏剧节", "description": "各类戏剧节活动"},
        {"code": "folk_custom", "name": "民俗活动", "description": "各类民俗文化活动"},
    ],
    "art_exhibition": [
        {"code": "painting_exhibition", "name": "美术展览", "description": "美术作品展览"},
        {"code": "calligraphy_exhibition", "name": "书法展览", "description": "书法作品展览"},
        {"code": "photography_exhibition", "name": "摄影展览", "description": "摄影作品展览"},
        {"code": "sculpture_exhibition", "name": "雕塑展览", "description": "雕塑作品展览"},
        {"code": "craft_exhibition", "name": "工艺展览", "description": "工艺美术展览"},
        {"code": "design_exhibition", "name": "设计展览", "description": "设计作品展览"},
        {"code": "digital_art", "name": "数字艺术", "description": "数字艺术展览"},
        {"code": "contemporary_art", "name": "当代艺术", "description": "当代艺术展览"},
        {"code": "ancient_art", "name": "古代艺术", "description": "古代艺术展览"},
        {"code": "cultural_relic", "name": "文物展览", "description": "文物精品展览"},
    ],
    "sports_event": [
        {"code": "olympic_games", "name": "奥运会", "description": "奥林匹克运动会"},
        {"code": "asian_games", "name": "亚运会", "description": "亚洲运动会"},
        {"code": "national_games", "name": "全运会", "description": "全国运动会"},
        {"code": "world_cup", "name": "世界杯", "description": "世界杯足球赛"},
        {"code": "championship", "name": "锦标赛", "description": "各类锦标赛"},
        {"code": "league_match", "name": "联赛", "description": "各类职业联赛"},
        {"code": "cup_match", "name": "杯赛", "description": "各类杯赛"},
        {"code": "international_match", "name": "国际赛事", "description": "国际体育赛事"},
        {"code": "domestic_match", "name": "国内赛事", "description": "国内体育赛事"},
        {"code": "amateur_match", "name": "业余赛事", "description": "业余体育赛事"},
    ],
    "fitness_exercise": [
        {"code": "public_fitness", "name": "全民健身", "description": "全民健身活动"},
        {"code": "running_activity", "name": "跑步活动", "description": "各类跑步活动"},
        {"code": "marathon", "name": "马拉松", "description": "马拉松赛事"},
        {"code": "fitness_class", "name": "健身课程", "description": "各类健身课程"},
        {"code": "yoga_activity", "name": "瑜伽活动", "description": "瑜伽健身活动"},
        {"code": "swimming_activity", "name": "游泳活动", "description": "游泳健身活动"},
        {"code": "ball_game", "name": "球类运动", "description": "各类球类运动"},
        {"code": "outdoor_activity", "name": "户外运动", "description": "户外运动活动"},
        {"code": "fitness_facility", "name": "健身设施", "description": "健身设施建设"},
        {"code": "fitness_guide", "name": "健身指导", "description": "科学健身指导"},
    ],
    "tourism_development": [
        {"code": "tourism_planning", "name": "旅游规划", "description": "旅游发展规划"},
        {"code": "tourism_policy", "name": "旅游政策", "description": "旅游发展政策"},
        {"code": "tourism_investment", "name": "旅游投资", "description": "旅游项目投资"},
        {"code": "tourism_marketing", "name": "旅游营销", "description": "旅游宣传营销"},
        {"code": "tourism_brand", "name": "旅游品牌", "description": "旅游品牌建设"},
        {"code": "tourism_standardization", "name": "旅游标准化", "description": "旅游服务标准化"},
        {"code": "smart_tourism", "name": "智慧旅游", "description": "智慧旅游建设"},
        {"code": "rural_tourism", "name": "乡村旅游", "description": "乡村旅游发展"},
        {"code": "cultural_tourism", "name": "文化旅游", "description": "文化旅游融合"},
        {"code": "tourism_statistics", "name": "旅游统计", "description": "旅游统计数据"},
    ],
    "scenic_dynamic": [
        {"code": "scenic_introduction", "name": "景区介绍", "description": "旅游景区介绍"},
        {"code": "scenic_activity", "name": "景区活动", "description": "景区特色活动"},
        {"code": "ticket_information", "name": "门票信息", "description": "景区门票信息"},
        {"code": "opening_hours", "name": "开放时间", "description": "景区开放时间"},
        {"code": "traffic_guide", "name": "交通指南", "description": "景区交通指南"},
        {"code": "service_facility", "name": "服务设施", "description": "景区服务设施"},
        {"code": "scenic_news", "name": "景区动态", "description": "景区最新动态"},
        {"code": "tourist_guide", "name": "游客指南", "description": "游客出行指南"},
        {"code": "hotel_information", "name": "住宿信息", "description": "景区周边住宿"},
        {"code": "specialty_product", "name": "特色产品", "description": "旅游特色产品"},
    ],
    "environmental_protection": [
        {"code": "air_pollution", "name": "大气污染", "description": "大气污染防治"},
        {"code": "water_pollution", "name": "水污染", "description": "水污染防治"},
        {"code": "soil_pollution", "name": "土壤污染", "description": "土壤污染防治"},
        {"code": "noise_pollution", "name": "噪声污染", "description": "噪声污染防治"},
        {"code": "solid_waste", "name": "固废处理", "description": "固体废物处理"},
        {"code": "environmental_monitoring", "name": "环境监测", "description": "环境质量监测"},
        {"code": "environmental_impact", "name": "环评", "description": "环境影响评价"},
        {"code": "environmental_law", "name": "环保执法", "description": "环境保护执法"},
        {"code": "carbon_neutral", "name": "碳中和", "description": "碳达峰碳中和"},
        {"code": "environmental_education", "name": "环保宣传", "description": "环保宣传教育"},
    ],
    "ecological_construction": [
        {"code": "forest_ecology", "name": "森林生态", "description": "森林生态保护"},
        {"code": "grassland_ecology", "name": "草原生态", "description": "草原生态保护"},
        {"code": "wetland_ecology", "name": "湿地生态", "description": "湿地生态保护"},
        {"code": "river_ecology", "name": "河流生态", "description": "河流生态保护"},
        {"code": "desert_ecology", "name": "荒漠生态", "description": "荒漠生态保护"},
        {"code": "biodiversity", "name": "生物多样性", "description": "生物多样性保护"},
        {"code": "nature_reserve", "name": "自然保护区", "description": "自然保护区建设"},
        {"code": "ecological_restoration", "name": "生态修复", "description": "生态系统修复"},
        {"code": "soil_erosion", "name": "水土流失", "description": "水土流失治理"},
        {"code": "desertification", "name": "荒漠化", "description": "荒漠化治理"},
    ],
    "transport_construction": [
        {"code": "highway_construction", "name": "公路建设", "description": "公路基础设施建设"},
        {"code": "railway_construction", "name": "铁路建设", "description": "铁路基础设施建设"},
        {"code": "aviation_construction", "name": "民航建设", "description": "民用航空建设"},
        {"code": "waterway_construction", "name": "水运建设", "description": "水路交通建设"},
        {"code": "urban_transport", "name": "城市交通", "description": "城市交通建设"},
        {"code": "metro_construction", "name": "地铁建设", "description": "城市轨道交通"},
        {"code": "bridge_tunnel", "name": "桥隧工程", "description": "桥梁隧道工程"},
        {"code": "transport_hub", "name": "交通枢纽", "description": "综合交通枢纽"},
        {"code": "intelligent_transport", "name": "智能交通", "description": "智能交通系统"},
        {"code": "transport_planning", "name": "交通规划", "description": "交通发展规划"},
    ],
    "traffic_accident": [
        {"code": "road_accident", "name": "道路事故", "description": "道路交通事故"},
        {"code": "rail_accident", "name": "铁路事故", "description": "铁路交通事故"},
        {"code": "aviation_accident", "name": "航空事故", "description": "民用航空事故"},
        {"code": "water_accident", "name": "水上事故", "description": "水上交通事故"},
        {"code": "accident_investigation", "name": "事故调查", "description": "交通事故调查"},
        {"code": "accident_responsibility", "name": "责任认定", "description": "事故责任认定"},
        {"code": "accident_compensation", "name": "事故赔偿", "description": "交通事故赔偿"},
        {"code": "traffic_violation", "name": "交通违法", "description": "交通违法行为"},
        {"code": "drunk_driving", "name": "酒驾醉驾", "description": "酒驾醉驾查处"},
        {"code": "accident_education", "name": "事故警示", "description": "交通事故警示"},
    ],
    "safety_production": [
        {"code": "safety_supervision", "name": "安全监管", "description": "安全生产监管"},
        {"code": "safety_inspection", "name": "安全检查", "description": "安全生产检查"},
        {"code": "safety_training", "name": "安全培训", "description": "安全生产培训"},
        {"code": "safety_responsibility", "name": "安全责任", "description": "安全生产责任制"},
        {"code": "safety_standardization", "name": "安全标准化", "description": "安全生产标准化"},
        {"code": "safety_emergency", "name": "应急救援", "description": "应急救援预案"},
        {"code": "safety_equipment", "name": "安全设备", "description": "安全设施设备"},
        {"code": "safety_culture", "name": "安全文化", "description": "安全文化建设"},
        {"code": "occupational_safety", "name": "职业安全", "description": "职业健康安全"},
        {"code": "safety_award", "name": "安全奖励", "description": "安全生产奖励"},
    ],
    "disaster_accident": [
        {"code": "earthquake", "name": "地震灾害", "description": "地震灾害事件"},
        {"code": "flood", "name": "洪涝灾害", "description": "洪涝灾害事件"},
        {"code": "drought", "name": "干旱灾害", "description": "干旱灾害事件"},
        {"code": "typhoon", "name": "台风灾害", "description": "台风灾害事件"},
        {"code": "hailstorm", "name": "冰雹灾害", "description": "冰雹灾害事件"},
        {"code": "landslide", "name": "地质灾害", "description": "地质灾害事件"},
        {"code": "forest_fire", "name": "森林火灾", "description": "森林火灾事件"},
        {"code": "grassland_fire", "name": "草原火灾", "description": "草原火灾事件"},
        {"code": "biological_disaster", "name": "生物灾害", "description": "生物灾害事件"},
        {"code": "disaster_relief", "name": "灾害救援", "description": "灾害救援工作"},
    ],
    "social_security": [
        {"code": "public_security", "name": "公共安全", "description": "公共安全防控"},
        {"code": "security_patrol", "name": "治安巡逻", "description": "治安巡逻防控"},
        {"code": "special_action", "name": "专项行动", "description": "治安专项行动"},
        {"code": "security_prevention", "name": "治安防范", "description": "治安防范工作"},
        {"code": "community_police", "name": "社区警务", "description": "社区警务工作"},
        {"code": "security_management", "name": "治安管理", "description": "治安管理处罚"},
        {"code": "border_control", "name": "边境管理", "description": "边境治安管理"},
        {"code": "exit_entry", "name": "出入境管理", "description": "出入境管理工作"},
        {"code": "security_technology", "name": "科技强警", "description": "科技强警建设"},
        {"code": "police_construction", "name": "队伍建设", "description": "公安队伍建设"},
    ],
    "judicial_case": [
        {"code": "criminal_case", "name": "刑事案件", "description": "刑事犯罪案件"},
        {"code": "civil_case", "name": "民事案件", "description": "民事纠纷案件"},
        {"code": "administrative_case", "name": "行政案件", "description": "行政诉讼案件"},
        {"code": "economic_case", "name": "经济案件", "description": "经济纠纷案件"},
        {"code": "intellectual_property", "name": "知识产权", "description": "知识产权案件"},
        {"code": "labor_dispute", "name": "劳动争议", "description": "劳动争议案件"},
        {"code": "traffic_case", "name": "交通案件", "description": "交通事故案件"},
        {"code": "judicial_reform", "name": "司法改革", "description": "司法体制改革"},
        {"code": "judicial_openness", "name": "司法公开", "description": "司法公开工作"},
        {"code": "judicial_aid", "name": "法律援助", "description": "法律援助服务"},
    ],
    "social_insurance": [
        {"code": "pension_insurance", "name": "养老保险", "description": "养老保险制度"},
        {"code": "medical_insurance", "name": "医疗保险", "description": "医疗保险制度"},
        {"code": "unemployment_insurance", "name": "失业保险", "description": "失业保险制度"},
        {"code": "work_injury_insurance", "name": "工伤保险", "description": "工伤保险制度"},
        {"code": "maternity_insurance", "name": "生育保险", "description": "生育保险制度"},
        {"code": "housing_fund", "name": "住房公积金", "description": "住房公积金制度"},
        {"code": "social_assistance", "name": "社会救助", "description": "社会救助制度"},
        {"code": "social_welfare", "name": "社会福利", "description": "社会福利事业"},
        {"code": "preferential_treatment", "name": "优抚安置", "description": "优抚安置工作"},
        {"code": "charity_cause", "name": "慈善事业", "description": "慈善事业发展"},
    ],
    "people_livelihood": [
        {"code": "employment_service", "name": "就业服务", "description": "就业创业服务"},
        {"code": "education_service", "name": "教育服务", "description": "教育公共服务"},
        {"code": "medical_service", "name": "医疗服务", "description": "医疗公共服务"},
        {"code": "elderly_service", "name": "养老服务", "description": "养老服务体系"},
        {"code": "child_service", "name": "儿童服务", "description": "儿童关爱服务"},
        {"code": "disabled_service", "name": "残疾人服务", "description": "残疾人服务"},
        {"code": "housing_security", "name": "住房保障", "description": "住房保障工作"},
        {"code": "community_service", "name": "社区服务", "description": "社区服务建设"},
        {"code": "convenience_service", "name": "便民服务", "description": "便民利民服务"},
        {"code": "price_stability", "name": "物价稳定", "description": "物价稳定工作"},
    ],
    "rural_revitalization": [
        {"code": "industrial_development", "name": "产业发展", "description": "乡村产业发展"},
        {"code": "talent_revitalization", "name": "人才振兴", "description": "乡村人才振兴"},
        {"code": "cultural_revitalization", "name": "文化振兴", "description": "乡村文化振兴"},
        {"code": "ecological_revitalization", "name": "生态振兴", "description": "乡村生态振兴"},
        {"code": "organizational_revitalization", "name": "组织振兴", "description": "乡村组织振兴"},
        {"code": "poverty_alleviation", "name": "脱贫攻坚", "description": "脱贫攻坚成果"},
        {"code": "rural_governance", "name": "乡村治理", "description": "乡村治理体系"},
        {"code": "rural_construction", "name": "乡村建设", "description": "乡村建设行动"},
        {"code": "rural_finance", "name": "农村金融", "description": "农村金融服务"},
        {"code": "rural_land", "name": "农村土地", "description": "农村土地制度"},
    ],
    "urban_construction": [
        {"code": "urban_planning", "name": "城市规划", "description": "城市总体规划"},
        {"code": "infrastructure", "name": "基础设施", "description": "城市基础设施"},
        {"code": "urban_renewal", "name": "城市更新", "description": "城市更新改造"},
        {"code": "urban_management", "name": "城市管理", "description": "城市精细化管理"},
        {"code": "urban_environment", "name": "城市环境", "description": "城市环境整治"},
        {"code": "urban_traffic", "name": "城市交通", "description": "城市交通管理"},
        {"code": "housing_development", "name": "住房建设", "description": "住房建设发展"},
        {"code": "community_construction", "name": "社区建设", "description": "社区建设工作"},
        {"code": "smart_city", "name": "智慧城市", "description": "智慧城市建设"},
        {"code": "urban_culture", "name": "城市文化", "description": "城市文化建设"},
    ],
    "market_supervision": [
        {"code": "market_access", "name": "市场准入", "description": "市场准入管理"},
        {"code": "market_order", "name": "市场秩序", "description": "市场秩序规范"},
        {"code": "price_supervision", "name": "价格监管", "description": "价格监督检查"},
        {"code": "anti_monopoly", "name": "反垄断", "description": "反垄断执法"},
        {"code": "anti_unfair_competition", "name": "反不正当竞争", "description": "反不正当竞争"},
        {"code": "ad_supervision", "name": "广告监管", "description": "广告监督管理"},
        {"code": "contract_supervision", "name": "合同监管", "description": "合同监督管理"},
        {"code": "intellectual_property_protection", "name": "知识产权保护", "description": "知识产权保护"},
        {"code": "quality_supervision", "name": "质量监管", "description": "产品质量监管"},
        {"code": "standardization", "name": "标准化", "description": "标准化管理工作"},
    ],
    "consumer_rights": [
        {"code": "consumer_complaint", "name": "消费投诉", "description": "消费者投诉处理"},
        {"code": "consumer_education", "name": "消费教育", "description": "消费教育引导"},
        {"code": "product_quality", "name": "产品质量", "description": "产品质量问题"},
        {"code": "service_quality", "name": "服务质量", "description": "服务质量问题"},
        {"code": "price_fraud", "name": "价格欺诈", "description": "价格欺诈行为"},
        {"code": "false_advertising", "name": "虚假宣传", "description": "虚假宣传行为"},
        {"code": "contract_dispute", "name": "合同纠纷", "description": "消费合同纠纷"},
        {"code": "after_sales_service", "name": "售后服务", "description": "售后服务问题"},
        {"code": "consumer_association", "name": "消协组织", "description": "消费者协会工作"},
        {"code": "consumer_rights_day", "name": "315活动", "description": "消费者权益日活动"},
    ],
    "weather_warning": [
        {"code": "rainstorm_warning", "name": "暴雨预警", "description": "暴雨天气预警"},
        {"code": "typhoon_warning", "name": "台风预警", "description": "台风天气预警"},
        {"code": "cold_wave_warning", "name": "寒潮预警", "description": "寒潮天气预警"},
        {"code": "high_temperature_warning", "name": "高温预警", "description": "高温天气预警"},
        {"code": "hail_warning", "name": "冰雹预警", "description": "冰雹天气预警"},
        {"code": "thunderstorm_warning", "name": "雷电预警", "description": "雷电天气预警"},
        {"code": "fog_warning", "name": "大雾预警", "description": "大雾天气预警"},
        {"code": "sandstorm_warning", "name": "沙尘预警", "description": "沙尘天气预警"},
        {"code": "snowstorm_warning", "name": "暴雪预警", "description": "暴雪天气预警"},
        {"code": "weather_forecast", "name": "天气预报", "description": "日常天气预报"},
    ],
    "emergency_event": [
        {"code": "emergency_response", "name": "应急响应", "description": "突发事件响应"},
        {"code": "emergency_disposal", "name": "应急处置", "description": "突发事件处置"},
        {"code": "emergency_rescue", "name": "应急救援", "description": "应急救援行动"},
        {"code": "emergency_medical", "name": "医疗救援", "description": "医疗救援工作"},
        {"code": "emergency_transport", "name": "交通保障", "description": "应急交通保障"},
        {"code": "emergency_supply", "name": "物资保障", "description": "应急物资保障"},
        {"code": "emergency_communication", "name": "通信保障", "description": "应急通信保障"},
        {"code": "emergency_evacuation", "name": "人员疏散", "description": "人员疏散安置"},
        {"code": "emergency_investigation", "name": "事故调查", "description": "事故原因调查"},
        {"code": "emergency_summary", "name": "事件总结", "description": "突发事件总结"},
    ],
}


def get_total_subcategories() -> int:
    """Get total number of subcategories."""
    total = 0
    for subcats in EVENT_SUBCATEGORIES.values():
        total += len(subcats)
    return total


if __name__ == "__main__":
    print(f"Total categories: {len(EVENT_CATEGORIES)}")
    print(f"Total subcategories: {get_total_subcategories()}")

    print("\nSample categories:")
    for cat in EVENT_CATEGORIES[:5]:
        subcats = EVENT_SUBCATEGORIES.get(cat["code"], [])
        print(f"  {cat['name']} ({cat['code']}): {len(subcats)} subcategories")
